version: "3.9"
services:

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    restart: on-failure
    # command: ["/wait-for-it.sh", "db:3309"]
    networks:
      - "hunwo"
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'hyunwoo-mysql2'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'coupang'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'coupang'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_TCP_PORT: '3306'

    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    # volumes:
    #   - my-db:/var/lib/mysql
    container_name: 'hyunwoo'
    networks:
      - "hunwo"
# volumes:
#   my-db:
networks:
  hunwo:
    driver: bridge