spring:
  datasource:
    url: jdbc:mysql://db:3306/hyunwoo-mysql2?serverTimezone=UTC
    username: coupang
    password: coupang
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
